name: Test github action call with fixed boolean inputs

on:
  workflow_dispatch:
  push:
  schedule:
  - cron: '9 0 * * 3'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      passed_true: true
      passed_false: false
