name: Test github action call with fixed boolean inputs

on:
  workflow_dispatch:
  push:

jobs:
  test:
    uses: ./.github/workflows/build.yaml
    with:
      passed_true: true
      passed_false: false
